version: '3.7'

services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13306:3306"
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "16379:6379"

  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "12379:2379"