apiVersion: v1
kind: Service
metadata:
  name: gohub-mysql
spec:
  selector:
    app: gohub-mysql
  ports:
    - protocol: TCP
      port: 13306
      targetPort: 3306
      nodePort: 30001
  type: NodePort
  