apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webook
  template:
    metadata:
      labels:
        app: webook
#        pod 具体信息
    spec:
      containers:
        - name: webook
          image: andras/webook:v0.0.1
          ports:
            - containerPort: 8080
