apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webook-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
#  使用nginx
  ingressClassName: nginx
  rules:
#    host 是webook.com 命中
    - host: webook.com
      http:
        paths:
#          请求路径是/ 转发到webook
          - backend:
              service:
                name: webook
                port:
                  number: 81
            pathType: Prefix
            path: /x
                