apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohub-mysql
  labels:
    app: gohub-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohub-mysql
  template:
    metadata:
      name: gohub-mysql
      labels:
        app: gohub-mysql
    spec:
      containers:
        - name: gohub-mysql
          image: mysql:8.0.29
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          imagePullPolicy: IfNotPresent
          volumeMounts:
#            - mysql 数据存储位置
            - mountPath: /var/lib/mysql
              name: gohub-mysql-volume
          ports:
            - containerPort: 3306
      restartPolicy: Always
#       pod 有哪些volumes
      volumes:
        - name: gohub-mysql-volume
          persistentVolumeClaim:
            claimName: gohub-mysql-pvc
      