apiVersion: v1
#k8s有哪些volume
kind: PersistentVolume
metadata:
  name: my-local-pv
  labels:
    app: my-local-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/live
  