---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 16840.
--- DateTime: 2024/7/25 22:43
---
---
local key = KEYS[1]
--验证次数
local cntKey = key .. ":cnt"

local val=ARGV[1]

local ttl = tonumber(redis.call("ttl", key))
if ttl == -1 then
    --key存在,过期时间不存在
    return -2
    --过期时间小于540s
elseif ttl == -2 or ttl < 540 then

    redis.call("set", key, val, "ex", 600)
    redis.call("set", cntKey, 3, "ex", 600)
    return 0
else
    --发送频繁
    return -1
end