---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 16840.
--- DateTime: 2024/7/25 23:39
---
local key = KEYS[1]
local expectedCode = ARGV[1]
local cntKey = key .. ':cnt'
local cnt = tonumber(redis.call('get', cntKey))
local code = redis.call('get', key)

if cnt == nil or cnt <= 0 then
    return -1
end

if code == expectedCode then
    redis.call('set',cntKey,-1)
    return 0
else
    redis.call('decr',cntKey)
    return -2
end
